# README FIRST
# 1. Subscribe to https://github.com/ansible-collections/news-for-maintainers
#    (click the Watch button on the homepage > Custom > Issues)
#    and keep this matrix up to date in accordance to related announcements.
#    Timely add new ansible-core versions and consider dropping support
#    and testing against its EOL versions.
# 2. If your collection repository is under the ansible-collections org,
#    please keep in mind that the number of GHA jobs is limited
#    and shared across all the collections in the org.
#    So, focusing on good test coverage of your collection,
#    please avoid testing against unnecessary entities such as
#    ansible-core EOL versions your collection does not support
#    or ansible-core versions that are not EOL yet but not supported by the collection.
# 3. If you don't have unit or integration tests, remove corresponding sections.
# 4. If your collection depends on other collections ensure they are installed,
#    add them to the "test-deps" input.
# 5. For the comprehensive list of the inputs supported by the
#    ansible-community/ansible-test-gh-action GitHub Action, see
#    https://github.com/marketplace/actions/ansible-test.
# 6. If you want to prevent merging PRs that do not pass all tests,
#    make sure to add the "check" job to your repository branch
#    protection once this workflow is added.
#    It is also possible to tweak which jobs are allowed to fail. See
#    https://github.com/marketplace/actions/alls-green#gotchas for more detail.
# 7. If you need help please ask in #community:ansible.com on Matrix
#    or in bridged #ansible-community on the Libera.Chat IRC channel.
#    See https://docs.ansible.com/ansible/devel/community/communication.html
#    for details.
# 8. If your collection is [going to get] included in the Ansible package,
#    it has to adhere to Python compatibility and CI testing requirements described in
#    https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html.

name: Integration
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
    branches:
      - main
  pull_request:
  # Run CI once per day (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still
  # testing against latest version of ansible-test for each ansible-core
  # version
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true

jobs:
  # Jobs need to be run serially due to using the free tier of DMS
  # integration:
  #   name: Integration (Ⓐ${{ matrix.ansible }})
  #   strategy:
  #     matrix:
  #       ansible:
  #         - stable-2.17
  #         - stable-2.18
  #         - stable-2.19
  #         - devel
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Perform integration testing
  #       # See the documentation for the following GitHub action on
  #       # https://github.com/ansible-community/ansible-test-gh-action/blob/main/README.md
  #       uses: ansible-community/ansible-test-gh-action@release/v1
  #       with:
  #         ansible-core-version: ${{ matrix.ansible }}
  #         testing-type: integration
  #         pull-request-change-detection: false
  #         coverage: never
  #         pre-test-cmd: ./tests/integration/generate_integration_config.sh
  #       env:
  #         DMS_API_KEY: ${{ secrets.DMS_API_KEY }}

  integration-217:
    name: Integration (Ⓐ2.17)
    runs-on: ubuntu-latest
    steps:
      - name: Perform integration testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: 2.17
          testing-type: integration
          pull-request-change-detection: false
          coverage: never
          pre-test-cmd: ./tests/integration/generate_integration_config.sh
        env:
          DMS_API_KEY: ${{ secrets.DMS_API_KEY }}

  integration-218:
    needs: [integration-217]
    name: Integration (Ⓐ2.18)
    runs-on: ubuntu-latest
    steps:
      - name: Perform integration testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: 2.18
          testing-type: integration
          pull-request-change-detection: false
          coverage: never
          pre-test-cmd: ./tests/integration/generate_integration_config.sh
        env:
          DMS_API_KEY: ${{ secrets.DMS_API_KEY }}

  integration-219:
    needs: [integration-218]
    name: Integration (Ⓐ2.19)
    runs-on: ubuntu-latest
    steps:
      - name: Perform integration testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: 2.19
          testing-type: integration
          pull-request-change-detection: false
          coverage: never
          pre-test-cmd: ./tests/integration/generate_integration_config.sh
        env:
          DMS_API_KEY: ${{ secrets.DMS_API_KEY }}

  integration-devel:
    needs: [integration-219]
    name: Integration (Ⓐdevel)
    runs-on: ubuntu-latest
    steps:
      - name: Perform integration testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: devel
          testing-type: integration
          pull-request-change-detection: false
          coverage: never
          pre-test-cmd: ./tests/integration/generate_integration_config.sh
        env:
          DMS_API_KEY: ${{ secrets.DMS_API_KEY }}

  # This job does nothing and is only used for the branch protection
  # or multi-stage CI jobs, like making sure that all tests pass before
  # a publishing job is started.
  integration-check:
    if: always()

    needs:
      - integration-217
      - integration-218
      - integration-219
      - integration-devel

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
